---
s3_location: ecmwf
s3_url: "https://storage.{{ s3_location }}.europeanweather.cloud"
s3_access_key: "{{ lookup('cypher','secret=secret/s3accesskey') | default('changeme') }}" # DEVMODE : disable this
s3_secret_key: "{{ lookup('cypher','secret=secret/s3secretkey') | default('changeme') }}" # DEVMODE : disable this
# s3_access_key: "{{ s3accesskey }}" # DEVMODE : enable this
# s3_secret_key: "{{ s3secretkey }}" # DEVMODE : enable this
